import React from 'react';
import {BoltIcon} from '@heroicons/react/24/outline';

const Brief = () => {
  return (
    <section className="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
      <div className="flex items-center mb-4">
        <div className="p-2 bg-purple-100 text-purple-600 rounded-lg mr-3">
          <BoltIcon className="w-6 h-6"/>
        </div>
        <h3 className="text-xl font-semibold text-slate-800">AI Pilot Briefing</h3>
      </div>

      {/*{briefing.loading ? (*/}
      {/*  <div className="animate-pulse space-y-3">*/}
      {/*    <div className="h-4 bg-slate-100 rounded w-3/4"></div>*/}
      {/*    <div className="h-4 bg-slate-100 rounded w-full"></div>*/}
      {/*    <div className="h-4 bg-slate-100 rounded w-5/6"></div>*/}
      {/*  </div>*/}
      {/*) : briefing.data ? (*/}
      {/*  <div className="prose prose-slate text-slate-600 max-w-none leading-relaxed whitespace-pre-line">*/}
      {/*    {briefing.data}*/}
      {/*  </div>*/}
      {/*) : (*/}
      {/*  <p className="text-slate-400 italic">Briefing information unavailable.</p>*/}
      {/*)}*/}
      <p className="mt-4 text-xs text-slate-400 uppercase tracking-wider">Generated by Gemini 2.5 Flash</p>
    </section>
  );
};

export default Brief;